services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:?}
        - GROUP_ID=${GROUP_ID:?}
    working_dir: /app
    command: bash webui.sh
    volumes:
      - ../webui:/app
      - ../.cache:/home/ai-user/.cache
    ports:
      - 7860:7860
    environment:
      - PYTHONUNBUFFERED=1
      - COMMANDLINE_ARGS=${COMMANDLINE_ARGS:?}
      - DISABLE_TELEMETRY=YES
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
